[package]
name = "dash-mpd-cli"
version = "0.2.21"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
license = "MIT"
description = "Download media content from a DASH-MPEG or DASH-WebM MPD manifest."
readme = "README.md"
repository = "https://github.com/emarsden/dash-mpd-cli"
documentation = "https://emarsden.github.io/dash-mpd-cli/"
keywords = ["video", "streaming", "DASH", "MPEG", "download"]
categories = ["command-line-utilities", "multimedia", "multimedia::video"]
edition = "2021"
publish = true


[dependencies]
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros"] }
tracing = { version = "0.1.40", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
time = { version = "0.3.36", features = ["local-offset"] }
dash-mpd = { version = "0.16.6", default-features = false, features = ["fetch", "compression", "rustls-tls", "scte35"] }
reqwest = { version = "0.12.5", default-features = false, features = ["gzip", "rustls-tls", "socks", "json", "cookies"] }
# We need to stay synchronized with the version used in the decrypt-cookies crate.
strum = { version = "0.26.3", features = ["derive"] }
colored = "2.1.0"
indicatif = "0.17.8"
clap = { version = "=4.3.24", features = ["cargo", "unicode", "wrap_help"] }
serde_json = "1.0.120"
versions = "6.3.0"
fs-err = "2.11.0"
number_prefix = "0.4.0"
anyhow = "1.0.86"
tempfile = "3.10.1"
decrypt-cookies = { version = "0.6.0", features = ["reqwest"], optional = true }
pssh-box = { version = "0.1.8", default-features = false }


[dev-dependencies]
rustls = { version = "0.23.12", features = ["aws_lc_rs"] }
rustls-pki-types = "1.7.0"
rustls-pemfile = "2.1.2"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "time", "macros"] }
tokio-rustls = "0.26.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
test-log = { version = "0.2.16", features = ["trace"] }
http = "1.1.0"
hyper = "1.4.1"
hyper-util = "0.1.6"
axum = "0.7.5"
hyper-serve = { version = "0.6.2", features = ["tls-rustls"] }
axum-auth = "0.7"
quick-xml = { version = "0.36.1", features = ["serialize"] }
mp4 = "0.14.0"
lazy_static = "1.5.0"
ffprobe = "0.4.0"
file-format = { version = "0.25.0", features = ["reader"] }
json = "0.12.4"
assert_cmd = "2.0.15"
assert_fs = "1.1.2"
predicates = "3.1.2"

[features]
default = ["cookies"]
cookies = ["decrypt-cookies"]


[profile.release]
opt-level = "z"  # optimize for size
lto = "fat"
codegen-units = 1
