on: workflow_dispatch

# test building release binaries on various platforms (run manually from the Github web UI)
name: release-bin-manual

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install protobuf-compiler

      - uses: actions/checkout@v5
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: dash-mpd-cli
          include: LICENSE-MIT,README.md,CHANGELOG.md
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

